### ISSUE TITLE
depends issue

### ISSUE THREAD

**Issue by shawn7com** [cetic/6lbr-openwrt#3]
The Makefile not work in openwrt bb, 6lbr option not show when make menuconfig, when I modified the DEPENDS line like below(add "+kmod-usb-serial" before ftdi)，it work fine：
`DEPENDS:=+libncurses +kmod-tun +kmod-usb-serial +kmod-usb-serial-ftdi  +kmod-usb-acm +logrotate`

**Comment by laurentderu** [comment]
Thanks for reporting, it's now fixed in https://github.com/cetic/6lbr-openwrt/commit/3d60e8f54b56e88d1360e63899e35e76b0989494
